

// TOOL:     vlog2tf
// DATE:     Tue May 13 18:39:35 2025
 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   Toplevel_datapath_4bits
// DESIGN:   Toplevel_datapath_4bits
// FILENAME: Toplevel_datapath_4bits_tf.v
// PROJECT:  Circuito
// VERSION:  2.0
// This file is auto generated by Diamond


`timescale 1 ns / 1 ps

// Define Module for Test Fixture
module Toplevel_datapath_4bits_tf();

// Inputs
    reg [3:0] dados;
    reg [2:0] operacao;
    reg sel21_mux;
    reg sel12_demux;
    reg [1:0] addr;
    reg clk;
    reg rst;


// Outputs
    wire [3:0] result;
    wire carry_out;


// Bidirs


// Instantiate the UUT
// Please check and add your parameters manually
    Toplevel_datapath_4bits UUT (
        .dados(dados), 
        .operacao(operacao), 
        .sel21_mux(sel21_mux), 
        .sel12_demux(sel12_demux), 
        .addr(addr), 
        .clk(clk), 
        .rst(rst), 
        .result(result), 
        .carry_out(carry_out)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            dados = 4'b0111;
            operacao =3'b000;//AND
            sel21_mux = 0;
            sel12_demux = 0;
            addr = 2'b00;
            clk = 0;
            rst = 1;
			#10;
			
			dados = 4'b0111;
            operacao =3'b000; //AND
            sel21_mux = 0;
            sel12_demux = 0;
            addr = 2'b00; //rf=0
            clk = 0;
            rst = 1;
			
    end

endmodule // Toplevel_datapath_4bits_tf